name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_push_image_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t mumouchli2/frontend_customers_image:latest .
          docker push mumouchli2/frontend_customers_image:latest

      - name: Deploy to Docker Hub
        run: |
          # Check if the container exists
          if docker ps -a --filter "name=frontend_customers_container" --format '{{.Names}}' | grep -q "frontend_customers_container"; then
            docker stop frontend_customers_container
            docker rm frontend_customers_container
          fi
          
          # Create and run the container
          docker run -d --name frontend_customers_container -p 8080:80 mumouchli2/frontend_customers_image:latest
