name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t mumouchli2/frontend_customers_image:latest .
          docker push mumouchli2/frontend_customers_image:latest

      - name: Deploy to Docker Hub
        run: |
          docker pull mumouchli2/frontend_customers_image:latest

          # Add a delay of 5 seconds before stopping and removing the container
          sleep 5

          docker stop frontend_customers_container || true
          docker rm frontend_customers_container || true
          docker run -d --name frontend_customers_container -p 8080:80 mumouchli2/frontend_customers_image:latest
