name: Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t mumouchli2/frontend_customers_image:latest .
          docker push mumouchli2/frontend_customers_image:latest

